/**
 * Fixed, non-secret protocol contract for the Task 5.1 memory-isolated runner.
 *
 * This module deliberately contains no network, storage, auth-client or plugin
 * integration. Workers and the page bridge share these constants and pure
 * validators so that no caller can supply a host, path, role, phase or state
 * transition at runtime.
 */

export const PROTOCOL = "wp3-task51-memory-runner-v1" as const;

export const PRODUCTION_ORIGIN = "https://d.xrugc.com" as const;
export const LOGIN_PATH = "/v1/auth/login" as const;
export const LOGOUT_PATH = "/v1/auth/logout" as const;

export const REQUEST_TIMEOUT_MS = 15_000 as const;
export const PAGE_DEADLINE_MS = 30 * 60 * 1_000;
export const STAGE_B_MIN_REMAINING_EXECUTION_MS =
  PAGE_DEADLINE_MS + REQUEST_TIMEOUT_MS;
export const OPERATOR_AUTH_QUIET_PERIOD_MS = 16 * 60 * 1_000;
export const CLOCK_SKEW_MS = 120 * 1_000;
export const MIN_TOKEN_TTL_MS = 35 * 60 * 1_000;
export const LOGIN_RESPONSE_MAX_BYTES = 64 * 1_024;
export const EVIDENCE_RESPONSE_MAX_BYTES = 8 * 1_024 * 1_024;

export const ROLES = ["user", "manager", "admin", "root"] as const;
export type RunnerRole = (typeof ROLES)[number];

export const NODES = ["xrteeth", "tmrpp"] as const;
export type RunnerNode = (typeof NODES)[number];

export const API_ORIGIN_BY_NODE = Object.freeze({
  xrteeth: "https://api.xrteeth.com",
  tmrpp: "https://api.tmrpp.com",
} as const satisfies Record<RunnerNode, string>);

/**
 * The Stage B coordinator is deliberately a single fixed origin. It must not
 * inherit the normal web proxy failover because two coordinators would make a
 * global one-shot claim split-brain by construction.
 */
export const STAGE_B_COORDINATOR_ORIGIN = API_ORIGIN_BY_NODE.xrteeth;
export const STAGE_B_COORDINATOR_CLAIM_PATH =
  "/v1/task51/stage-b/claim" as const;

export const LOGIN_HOST_BY_ROLE = Object.freeze({
  user: API_ORIGIN_BY_NODE.xrteeth,
  manager: API_ORIGIN_BY_NODE.xrteeth,
  admin: API_ORIGIN_BY_NODE.tmrpp,
  root: API_ORIGIN_BY_NODE.tmrpp,
} as const satisfies Record<RunnerRole, string>);

export const EVIDENCE_PATHS = [
  "/v1/user/info",
  "/v1/plugin/verify-token",
  "/v1/organization/list",
] as const;
export type EvidencePath = (typeof EVIDENCE_PATHS)[number];

export const EVIDENCE_PHASES = ["readiness", "baseline", "shadow"] as const;
export type EvidencePhase = (typeof EVIDENCE_PHASES)[number];

export const RUNNER_STATES = [
  "BOOTSTRAP",
  "PREFLIGHT",
  "CAPTURE_USER",
  "CAPTURE_MANAGER",
  "CAPTURE_ADMIN",
  "CAPTURE_ROOT",
  "READINESS_VERIFIED",
  "BASELINE_READY",
  "XRTEETH_SHADOW_RUNNING",
  "WAIT_XRTEETH_RESTORED",
  "TMRPP_SHADOW_RUNNING",
  "COMPLETE",
  "FAILED_TERMINAL",
  "CLEARING",
  "CLEARED",
] as const;
export type RunnerState = (typeof RUNNER_STATES)[number];

const NORMAL_TRANSITIONS = Object.freeze({
  BOOTSTRAP: "PREFLIGHT",
  PREFLIGHT: "CAPTURE_USER",
  CAPTURE_USER: "CAPTURE_MANAGER",
  CAPTURE_MANAGER: "CAPTURE_ADMIN",
  CAPTURE_ADMIN: "CAPTURE_ROOT",
  CAPTURE_ROOT: "READINESS_VERIFIED",
  READINESS_VERIFIED: "BASELINE_READY",
  BASELINE_READY: "XRTEETH_SHADOW_RUNNING",
  XRTEETH_SHADOW_RUNNING: "WAIT_XRTEETH_RESTORED",
  WAIT_XRTEETH_RESTORED: "TMRPP_SHADOW_RUNNING",
  TMRPP_SHADOW_RUNNING: "COMPLETE",
  COMPLETE: "CLEARING",
  FAILED_TERMINAL: "CLEARING",
  CLEARING: "CLEARED",
} as const satisfies Partial<Record<RunnerState, RunnerState>>);

const FAILURE_ELIGIBLE_STATES: ReadonlySet<RunnerState> = new Set([
  "BOOTSTRAP",
  "PREFLIGHT",
  "CAPTURE_USER",
  "CAPTURE_MANAGER",
  "CAPTURE_ADMIN",
  "CAPTURE_ROOT",
  "READINESS_VERIFIED",
  "BASELINE_READY",
  "XRTEETH_SHADOW_RUNNING",
  "WAIT_XRTEETH_RESTORED",
  "TMRPP_SHADOW_RUNNING",
  "COMPLETE",
]);

export function canTransitionRunnerState(
  from: RunnerState,
  to: RunnerState
): boolean {
  if (to === "FAILED_TERMINAL") {
    return FAILURE_ELIGIBLE_STATES.has(from);
  }
  return NORMAL_TRANSITIONS[from as keyof typeof NORMAL_TRANSITIONS] === to;
}

export function advanceRunnerState(
  from: RunnerState,
  to: RunnerState
): RunnerState {
  if (!canTransitionRunnerState(from, to)) {
    throw new Error(`TASK51_INVALID_STATE_TRANSITION:${from}:${to}`);
  }
  return to;
}

export type LedgerKey =
  `${EvidencePhase}|${RunnerNode}|${RunnerRole}|${EvidencePath}`;

export interface EvidenceLedgerCell {
  readonly index: number;
  readonly key: LedgerKey;
  readonly phase: EvidencePhase;
  readonly node: RunnerNode;
  readonly role: RunnerRole;
  readonly path: EvidencePath;
}

function makeLedgerKey(
  phase: EvidencePhase,
  node: RunnerNode,
  role: RunnerRole,
  path: EvidencePath
): LedgerKey {
  return `${phase}|${node}|${role}|${path}`;
}

/**
 * Builds the only permitted 56 logical evidence GETs in dispatch order.
 * OPTIONS generated by the browser are intentionally outside this ledger.
 */
export function buildEvidenceLedger(): readonly EvidenceLedgerCell[] {
  const cells: EvidenceLedgerCell[] = [];
  const append = (
    phase: EvidencePhase,
    node: RunnerNode,
    role: RunnerRole,
    path: EvidencePath
  ) => {
    const cell: EvidenceLedgerCell = Object.freeze({
      index: cells.length,
      key: makeLedgerKey(phase, node, role, path),
      phase,
      node,
      role,
      path,
    });
    cells.push(cell);
  };

  for (const node of NODES) {
    for (const role of ROLES) {
      append("readiness", node, role, "/v1/user/info");
    }
  }

  for (const node of NODES) {
    for (const role of ROLES) {
      for (const path of EVIDENCE_PATHS) {
        append("baseline", node, role, path);
      }
    }
  }

  // The node ordering is a safety property: xrteeth must be restored before
  // the bridge is allowed to dispatch the first tmrpp shadow cell.
  for (const node of NODES) {
    for (const role of ROLES) {
      for (const path of EVIDENCE_PATHS) {
        append("shadow", node, role, path);
      }
    }
  }

  if (cells.length !== 56 || new Set(cells.map(({ key }) => key)).size !== 56) {
    throw new Error("TASK51_INVALID_FIXED_LEDGER");
  }

  return Object.freeze(cells);
}

export const EVIDENCE_LEDGER = buildEvidenceLedger();

export interface EvidenceLedgerRuntime {
  readonly expectedKeys: ReadonlySet<LedgerKey>;
  readonly burnedKeys: Set<LedgerKey>;
}

export function createEvidenceLedgerRuntime(): EvidenceLedgerRuntime {
  return {
    expectedKeys: new Set(EVIDENCE_LEDGER.map(({ key }) => key)),
    burnedKeys: new Set<LedgerKey>(),
  };
}

/** Burn synchronously before fetch. Unknown and duplicate cells fail closed. */
export function burnLedgerCell(
  ledger: EvidenceLedgerRuntime,
  key: LedgerKey
): number {
  if (!ledger.expectedKeys.has(key)) {
    throw new Error(`TASK51_UNKNOWN_LEDGER_CELL:${key}`);
  }
  if (ledger.burnedKeys.has(key)) {
    throw new Error(`TASK51_DUPLICATE_LEDGER_CELL:${key}`);
  }
  ledger.burnedKeys.add(key);
  return ledger.burnedKeys.size;
}

export const EXTERNAL_GATE_KEYS = [
  "exactProductionOrigin",
  "operatorRootVerified",
  "warmSpaDocument",
  "operatorAuthQuietPeriodComplete",
  "evidenceFenceQuiet",
  "exclusiveLockAcquired",
  "serviceWorkerAbsent",
  "task33bEvidenceInherited",
  "task41ArtifactExact",
  "xrteethCorsExact",
  "tmrppCorsExact",
  "xrteethFullDefaultOff",
  "tmrppFullDefaultOff",
  "xrteethRevisionHealthyExact",
  "tmrppRevisionHealthyExact",
  "noCompetingWriter",
] as const;

export type ExternalGateKey = (typeof EXTERNAL_GATE_KEYS)[number];
export type ExternalGate = Readonly<Record<ExternalGateKey, boolean>>;

function isPlainRecord(value: unknown): value is Record<string, unknown> {
  if (value === null || typeof value !== "object") return false;
  const prototype = Object.getPrototypeOf(value);
  return prototype === Object.prototype || prototype === null;
}

/** Requires the exact key set and primitive booleans; truthy values fail. */
export function isExactExternalGate(value: unknown): value is ExternalGate {
  if (!isPlainRecord(value)) return false;
  const actualKeys = Object.keys(value).sort();
  const expectedKeys = [...EXTERNAL_GATE_KEYS].sort();
  if (
    actualKeys.length !== expectedKeys.length ||
    actualKeys.some((key, index) => key !== expectedKeys[index])
  ) {
    return false;
  }
  return EXTERNAL_GATE_KEYS.every((key) => typeof value[key] === "boolean");
}

export function externalGatesPass(value: unknown): value is ExternalGate {
  return (
    isExactExternalGate(value) &&
    EXTERNAL_GATE_KEYS.every((key) => value[key] === true)
  );
}

/**
 * Gates that must be acknowledged before the page is allowed to read the
 * first evidence credential. The four release/window keys deliberately live
 * only in this pre-capture contract: the later baseline gate remains a fresh
 * re-check of its existing runtime conditions.
 */
export const PREFLIGHT_GATE_KEYS = [
  ...EXTERNAL_GATE_KEYS,
  "stageAWebReleasePassedExact",
  "stageBOneShotApprovalExact",
  "stageBWindowCurrent",
  "stageBGlobalClaimExact",
] as const;

export type PreflightGateKey = (typeof PREFLIGHT_GATE_KEYS)[number];
export type PreflightGate = Readonly<Record<PreflightGateKey, boolean>>;

export const SHADOW_OPEN_GATE_KEYS = [
  "identityShadowExact",
  "backendRouteEnabledAfterIdentityShadow",
  "roleWriteDefaultOff",
  "organizationDefaultOff",
  "exactRevisionHealthy",
  "noCompetingWriter",
  "unexpectedTrafficZero",
] as const;
export type ShadowOpenGateKey = (typeof SHADOW_OPEN_GATE_KEYS)[number];
export type ShadowOpenGate = Readonly<Record<ShadowOpenGateKey, boolean>>;

export const XRTEETH_RESTORE_GATE_KEYS = [
  "backendRouteRestoredBeforeIdentityLegacy",
  "identityLegacyRestored",
  "authzFullDefaultOff",
  "roleWriteDefaultOff",
  "organizationDefaultOff",
  "exactRevisionHealthy",
  "nodeLocalCompletedPositive",
  "nodeLocalMismatchZero",
  "nodeLocalErrorZero",
  "nodeLocalFallbackZero",
  "nodeLocalPermissionUnionZero",
  "nodeLocalWriteZero",
  "unexpectedTrafficZero",
] as const;
export type XrteethRestoreGateKey = (typeof XRTEETH_RESTORE_GATE_KEYS)[number];
export type XrteethRestoreGate = Readonly<
  Record<XrteethRestoreGateKey, boolean>
>;

export const FINAL_RESTORE_GATE_KEYS = [
  "tmrppBackendRestoredBeforeIdentityLegacy",
  "tmrppIdentityLegacyRestored",
  "tmrppNodeLocalCompletedPositive",
  "tmrppNodeLocalMismatchZero",
  "tmrppNodeLocalErrorZero",
  "tmrppNodeLocalFallbackZero",
  "tmrppNodeLocalPermissionUnionZero",
  "tmrppNodeLocalWriteZero",
  "dualNodeAuthzFullDefaultOff",
  "dualNodeRoleWriteDefaultOff",
  "dualNodeOrganizationDefaultOff",
  "dualNodeExactRevisionsHealthy",
  "defaultOffCycleOnePassed",
  "defaultOffCycleTwoPassed",
  "unexpectedTrafficZero",
] as const;
export type FinalRestoreGateKey = (typeof FINAL_RESTORE_GATE_KEYS)[number];
export type FinalRestoreGate = Readonly<Record<FinalRestoreGateKey, boolean>>;

function exactBooleanGatePasses(
  value: unknown,
  expectedKeys: readonly string[]
): boolean {
  if (!isPlainRecord(value)) return false;
  const actualKeys = Object.keys(value).sort();
  const sortedExpected = [...expectedKeys].sort();
  return (
    actualKeys.length === sortedExpected.length &&
    actualKeys.every((key, index) => key === sortedExpected[index]) &&
    expectedKeys.every((key) => value[key] === true)
  );
}

export const preflightGatesPass = (value: unknown): value is PreflightGate =>
  exactBooleanGatePasses(value, PREFLIGHT_GATE_KEYS);

export const shadowOpenGatesPass = (value: unknown): value is ShadowOpenGate =>
  exactBooleanGatePasses(value, SHADOW_OPEN_GATE_KEYS);

export const xrteethRestoreGatesPass = (
  value: unknown
): value is XrteethRestoreGate =>
  exactBooleanGatePasses(value, XRTEETH_RESTORE_GATE_KEYS);

export const finalRestoreGatesPass = (
  value: unknown
): value is FinalRestoreGate =>
  exactBooleanGatePasses(value, FINAL_RESTORE_GATE_KEYS);

export const RUNNER_FAILURE_CODES = [
  "ORIGIN_REJECTED",
  "ROOT_GATE_REJECTED",
  "COLD_DOCUMENT_REJECTED",
  "EXTERNAL_GATE_REJECTED",
  "LOCK_UNAVAILABLE",
  "SERVICE_WORKER_ACTIVE",
  "INVALID_TRANSITION",
  "DUPLICATE_DISPATCH",
  "UNEXPECTED_TRAFFIC",
  "NETWORK_ERROR",
  "REDIRECT_REJECTED",
  "REQUEST_TIMEOUT",
  "PAGE_DEADLINE_EXCEEDED",
  "HTTP_STATUS_REJECTED",
  "RESPONSE_TOO_LARGE",
  "RESPONSE_SCHEMA_REJECTED",
  "ROLE_MISMATCH",
  "SUBJECT_MISMATCH",
  "DUPLICATE_BEARER",
  "TTL_INSUFFICIENT",
  "REVOKE_FAILED",
  "RESPONSE_PARITY_MISMATCH",
  "WORKER_ERROR",
  "LIFECYCLE_ABORT",
] as const;
export type RunnerFailureCode = (typeof RUNNER_FAILURE_CODES)[number];

export interface SafeCellResult {
  readonly ledgerKey: LedgerKey;
  readonly phase: EvidencePhase;
  readonly node: RunnerNode;
  readonly role: RunnerRole;
  readonly roleSubjectDigest: string;
  readonly path: EvidencePath;
  readonly httpStatus: number;
  readonly transportPassed: boolean;
  readonly schemaPassed: boolean;
  readonly expectedDecisionMatched: boolean;
  readonly baselineParityMatched: boolean | null;
  readonly roleExact: boolean | null;
  readonly crossNodeIdentityMatched: boolean | null;
}

export const STAGE_B_EXECUTION_EVIDENCE_SCHEMA =
  "wp3-task51-stage-b-execution-approval-v3" as const;
export const STAGE_B_GLOBAL_CLAIM_RECEIPT_SCHEMA =
  "wp3-task51-stage-b-global-claim-receipt-v1" as const;
export const RUNNER_FRAGMENT_SCHEMA = "wp3-task51-runner-fragment-v3" as const;
export const PRODUCTION_DIRECT_MATRIX_SCHEMA =
  "wp3-task51-production-direct-matrix-v1" as const;
export const STAGE_B_EXECUTION_EVIDENCE_MAX_BYTES = 16 * 1_024;
export const STAGE_B_GLOBAL_CLAIM_RECEIPT_MAX_BYTES = 8 * 1_024;
export const PRODUCTION_DIRECT_MATRIX_MAX_BYTES = 256 * 1_024;
export const PRODUCTION_DIRECT_MATRIX_CELL_COUNT = 256;
export const PRODUCTION_DIRECT_MATRIX_PHASES = [
  "before",
  "hit",
  "restore",
  "after",
] as const;
export const PRODUCTION_DIRECT_MATRIX_SURFACES = [
  "dynamicRoutes",
  "userManagement",
  "systemAdmin",
  "campusOrganization",
  "pluginVerifyToken",
  "permissionCheck",
  "iframe",
  "legacyResponseEnvelope",
] as const;
const PRODUCTION_DIRECT_MATRIX_ORDINARY_USER_DENIED_SURFACES = new Set<string>([
  "userManagement",
  "systemAdmin",
  "campusOrganization",
  "iframe",
]);
const PRODUCTION_DIRECT_MATRIX_KEYS = [
  "approvalRef",
  "capturedAt",
  "cellCount",
  "cells",
  "environment",
  "executionId",
  "fallbackAppliedCount",
  "mutationCount",
  "nodeCount",
  "nodePhases",
  "ordinaryUserNegativePassed",
  "permissionUnionAppliedCount",
  "phaseCount",
  "roleCount",
  "roleSubjectDigests",
  "rootBreakGlassPassed",
  "schema",
  "stageBExecutionEvidenceSha256",
  "subjectCount",
  "subjectDigest",
  "surfaceCount",
  "unexpected5xxCount",
] as const;
const PRODUCTION_DIRECT_MATRIX_NODE_PHASE_KEYS = [
  "authzMode",
  "backendHealthy",
  "backendPublishShaExact",
  "backendRouteIntegrationEnabled",
  "evidenceRef",
  "expectedBackendPublishSha",
  "expectedIdentityPublishSha",
  "fallbackAppliedCount",
  "identityHealthy",
  "identityPublishShaExact",
  "legacyResponseParityMatched",
  "mutationCount",
  "node",
  "observedAt",
  "observedBackendPublishSha",
  "observedIdentityPublishSha",
  "ordinal",
  "permissionUnionAppliedCount",
  "phase",
  "publicHealthPassed",
  "responseProvider",
  "runtimeExact",
  "sourceExact",
  "unexpected5xxCount",
] as const;
const PRODUCTION_DIRECT_MATRIX_CELL_KEYS = [
  "currentProduction",
  "directObserved",
  "evidenceRef",
  "expectedDecisionMatched",
  "fallbackApplied",
  "fresh",
  "ledgerKey",
  "legacyResponseParityMatched",
  "mutationCount",
  "node",
  "ordinaryUserPrivilegedDenied",
  "permissionUnionApplied",
  "phase",
  "role",
  "roleSubjectDigest",
  "rootBreakGlassPreserved",
  "surface",
  "unexpected5xxCount",
] as const;

const STAGE_B_EXECUTION_EVIDENCE_KEYS = [
  "approvalRef",
  "authorizedControlPostCount",
  "authorizedLogicalGetCount",
  "authorizedLoginCount",
  "authorizedLogoutCount",
  "claimCapabilitySha256",
  "coordinatorOrigin",
  "coordinatorServerPublishSha",
  "currentWindowOnly",
  "executionId",
  "expiresAt",
  "issuedAt",
  "oneShot",
  "productionDirectMatrixAuthorizedCellCount",
  "productionDirectMatrixEvidenceRef",
  "productionDirectMatrixSchema",
  "productionDirectMatrixSubjectDigest",
  "protocol",
  "schema",
  "stageAApprovalRef",
  "stageACoordinatorServerReleaseEvidenceSha256",
  "stageANetworkAttestorReleaseEvidenceSha256",
  "stageAReleaseEvidenceSha256",
  "status",
] as const;

export type StageBExecutionEvidence = Readonly<{
  schema: typeof STAGE_B_EXECUTION_EVIDENCE_SCHEMA;
  protocol: typeof PROTOCOL;
  approvalRef: string;
  authorizedControlPostCount: 1;
  authorizedLogicalGetCount: 56;
  authorizedLoginCount: 4;
  authorizedLogoutCount: 4;
  claimCapabilitySha256: string;
  coordinatorOrigin: typeof STAGE_B_COORDINATOR_ORIGIN;
  coordinatorServerPublishSha: string;
  currentWindowOnly: true;
  executionId: string;
  expiresAt: string;
  issuedAt: string;
  oneShot: true;
  productionDirectMatrixAuthorizedCellCount: 256;
  productionDirectMatrixEvidenceRef: string;
  productionDirectMatrixSchema: typeof PRODUCTION_DIRECT_MATRIX_SCHEMA;
  productionDirectMatrixSubjectDigest: string;
  stageAApprovalRef: string;
  stageACoordinatorServerReleaseEvidenceSha256: string;
  stageANetworkAttestorReleaseEvidenceSha256: string;
  stageAReleaseEvidenceSha256: string;
  status: "APPROVED";
}>;

const STAGE_B_GLOBAL_CLAIM_RECEIPT_KEYS = [
  "approvalRef",
  "claimCount",
  "claimedAt",
  "coordinatorOrigin",
  "coordinatorServerPublishSha",
  "executionId",
  "expiresAt",
  "globalExactOneClaimed",
  "schema",
  "stageBExecutionEvidenceSha256",
  "state",
] as const;

export type StageBGlobalClaimReceipt = Readonly<{
  schema: typeof STAGE_B_GLOBAL_CLAIM_RECEIPT_SCHEMA;
  approvalRef: string;
  executionId: string;
  state: "CLAIMED";
  globalExactOneClaimed: true;
  claimCount: 1;
  claimedAt: string;
  expiresAt: string;
  stageBExecutionEvidenceSha256: string;
  coordinatorOrigin: typeof STAGE_B_COORDINATOR_ORIGIN;
  coordinatorServerPublishSha: string;
}>;

export type RunnerFragmentCounts = Readonly<{
  baselineCellCount: 24;
  burnedLogicalGetCount: 56;
  captureCount: 4;
  completedLogicalGetCount: 56;
  duplicateCellCount: 0;
  expectedLogicalGetCount: 56;
  failedCellCount: 0;
  maxInFlightGetCount: 1;
  personalDataFindingCount: 0;
  readinessCellCount: 8;
  retryCount: 0;
  shadowCellCount: 24;
  tmrppShadowCellCount: 12;
  unknownCellCount: 0;
  unsafeFieldCount: 0;
  xrteethShadowCellCount: 12;
}>;

export type RunnerFragmentFlags = Readonly<{
  captureAcceptanceImpliesSuccessfulRevoke: true;
  cleared: true;
  completed: true;
  externalGatesPassedBeforeCapture: true;
  ordinaryUserNegativePassed: true;
  responseMaterialPersisted: false;
  responseMaterialPrintedOrLogged: false;
  rootBreakGlassPassed: true;
  safeOutputOnly: true;
  strictlySerial: true;
  workerReferencesCleared: true;
}>;

export type Task51RunnerFragment = Readonly<{
  schema: typeof RUNNER_FRAGMENT_SCHEMA;
  protocol: typeof PROTOCOL;
  approvalRef: string;
  executionId: string;
  stageBExecutionEvidenceSha256: string;
  stageBGlobalClaimReceiptSha256: string;
  stageBClaimedAt: string;
  productionDirectMatrixEvidenceRef: string;
  productionDirectMatrixEvidenceSha256: string;
  productionDirectMatrixSubjectDigest: string;
  exportedAt: string;
  safeCellResults: readonly SafeCellResult[];
  counts: RunnerFragmentCounts;
  flags: RunnerFragmentFlags;
}>;

const FRAGMENT_KEYS = [
  "approvalRef",
  "counts",
  "executionId",
  "exportedAt",
  "flags",
  "protocol",
  "productionDirectMatrixEvidenceRef",
  "productionDirectMatrixEvidenceSha256",
  "productionDirectMatrixSubjectDigest",
  "safeCellResults",
  "schema",
  "stageBClaimedAt",
  "stageBExecutionEvidenceSha256",
  "stageBGlobalClaimReceiptSha256",
] as const;

const FRAGMENT_COUNT_KEYS = [
  "baselineCellCount",
  "burnedLogicalGetCount",
  "captureCount",
  "completedLogicalGetCount",
  "duplicateCellCount",
  "expectedLogicalGetCount",
  "failedCellCount",
  "maxInFlightGetCount",
  "personalDataFindingCount",
  "readinessCellCount",
  "retryCount",
  "shadowCellCount",
  "tmrppShadowCellCount",
  "unknownCellCount",
  "unsafeFieldCount",
  "xrteethShadowCellCount",
] as const satisfies readonly (keyof RunnerFragmentCounts)[];

const FRAGMENT_FLAG_KEYS = [
  "captureAcceptanceImpliesSuccessfulRevoke",
  "cleared",
  "completed",
  "externalGatesPassedBeforeCapture",
  "ordinaryUserNegativePassed",
  "responseMaterialPersisted",
  "responseMaterialPrintedOrLogged",
  "rootBreakGlassPassed",
  "safeOutputOnly",
  "strictlySerial",
  "workerReferencesCleared",
] as const satisfies readonly (keyof RunnerFragmentFlags)[];

const SAFE_CELL_RESULT_KEYS = [
  "baselineParityMatched",
  "crossNodeIdentityMatched",
  "expectedDecisionMatched",
  "httpStatus",
  "ledgerKey",
  "node",
  "path",
  "phase",
  "role",
  "roleSubjectDigest",
  "roleExact",
  "schemaPassed",
  "transportPassed",
] as const satisfies readonly (keyof SafeCellResult)[];

function hasExactObjectKeys(
  value: Record<string, unknown>,
  expectedKeys: readonly string[]
): boolean {
  const actual = Object.keys(value).sort();
  const expected = [...expectedKeys].sort();
  return (
    actual.length === expected.length &&
    actual.every((key, index) => key === expected[index])
  );
}

export function isExactIsoInstant(value: unknown): value is string {
  if (typeof value !== "string") return false;
  const match =
    /^(\d{4})-(\d{2})-(\d{2})T(\d{2}):(\d{2}):(\d{2})(?:\.\d{3})?(Z|[+-](\d{2}):(\d{2}))$/.exec(
      value
    );
  if (!match) return false;
  const year = Number(match[1]);
  const month = Number(match[2]);
  const day = Number(match[3]);
  const hour = Number(match[4]);
  const minute = Number(match[5]);
  const second = Number(match[6]);
  const leap = year % 4 === 0 && (year % 100 !== 0 || year % 400 === 0);
  const days = [0, 31, leap ? 29 : 28, 31, 30, 31, 30, 31, 31, 30, 31, 30, 31];
  const offsetHour = match[7] === "Z" ? 0 : Number(match[8]);
  const offsetMinute = match[7] === "Z" ? 0 : Number(match[9]);
  return (
    year >= 1 &&
    month >= 1 &&
    month <= 12 &&
    day >= 1 &&
    day <= days[month] &&
    hour <= 23 &&
    minute <= 59 &&
    second <= 59 &&
    offsetHour <= 14 &&
    offsetMinute <= 59 &&
    (offsetHour < 14 || offsetMinute === 0) &&
    Number.isFinite(Date.parse(value))
  );
}

const STAGE_B_APPROVAL_PATTERN =
  /^WP3-TASK51-[A-Z0-9-]*MEMORY-RUNNER[A-Z0-9-]*STAGE-B-[0-9]{8}$/;
const STAGE_A_APPROVAL_PATTERN =
  /^WP3-REL-TASK51-[A-Z0-9-]*MEMORY-RUNNER[A-Z0-9-]*STAGE-A-[0-9]{8}$/;
const STAGE_B_EXECUTION_PATTERN = /^task51-stage-b-[a-z0-9-]{8,96}$/;

const matchesPattern = (value: unknown, pattern: RegExp): value is string =>
  typeof value === "string" && pattern.test(value);

/**
 * RFC-8259 JSON with recursively ASCII-sorted object keys, no insignificant
 * whitespace, UTF-8 encoding and exactly one trailing LF.
 */
export function encodeAsciiSortedCanonicalJson(value: unknown): Uint8Array {
  const render = (candidate: unknown): string => {
    if (candidate === null) return "null";
    if (typeof candidate === "boolean") return candidate ? "true" : "false";
    if (typeof candidate === "number") {
      if (!Number.isFinite(candidate)) {
        throw new Error("TASK51_CANONICAL_JSON_REJECTED");
      }
      return JSON.stringify(candidate);
    }
    if (typeof candidate === "string") return JSON.stringify(candidate);
    if (Array.isArray(candidate)) {
      return `[${candidate.map((entry) => render(entry)).join(",")}]`;
    }
    if (!isPlainRecord(candidate)) {
      throw new Error("TASK51_CANONICAL_JSON_REJECTED");
    }
    const keys = Object.keys(candidate).sort();
    if (keys.some((key) => !/^[\x20-\x7E]+$/.test(key))) {
      throw new Error("TASK51_CANONICAL_JSON_REJECTED");
    }
    return `{${keys
      .map((key) => `${JSON.stringify(key)}:${render(candidate[key])}`)
      .join(",")}}`;
  };

  return new TextEncoder().encode(`${render(value)}\n`);
}

function bytesEqual(left: Uint8Array, right: Uint8Array): boolean {
  return (
    left.byteLength === right.byteLength &&
    left.every((byte, index) => byte === right[index])
  );
}

export type ProductionDirectMatrixBinding = Readonly<{
  approvalRef: string;
  capturedAt: string;
  executionId: string;
  roleSubjectDigests: Readonly<Record<RunnerRole, string>>;
  stageBExecutionEvidenceSha256: string;
  subjectDigest: string;
}>;

const isProductionMatrixEvidenceRef = (value: unknown): value is string =>
  typeof value === "string" &&
  value.length <= 256 &&
  /^reports\/[A-Za-z0-9._/-]+\.json$/.test(value) &&
  !value
    .split("/")
    .some((segment) => segment === "" || segment === "." || segment === "..");

/** Fail-closed parser for the current-Production 2x4x4x8 direct matrix raw. */
export function parseProductionDirectMatrixEvidence(
  raw: Uint8Array,
  expected: Readonly<{
    approvalRef: string;
    executionId: string;
    stageBExecutionEvidenceSha256: string;
    subjectDigest: string;
  }>
): ProductionDirectMatrixBinding {
  const reject = (): never => {
    throw new Error("TASK51_PRODUCTION_DIRECT_MATRIX_REJECTED");
  };
  if (
    !isUint8ArrayBytes(raw) ||
    raw.byteLength === 0 ||
    raw.byteLength > PRODUCTION_DIRECT_MATRIX_MAX_BYTES
  )
    reject();
  let parsed: unknown;
  try {
    parsed = JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(raw));
  } catch {
    reject();
  }
  if (!isPlainRecord(parsed)) return reject();
  const matrix = parsed;
  if (
    !hasExactObjectKeys(matrix, PRODUCTION_DIRECT_MATRIX_KEYS) ||
    matrix.schema !== PRODUCTION_DIRECT_MATRIX_SCHEMA ||
    matrix.approvalRef !== expected.approvalRef ||
    matrix.executionId !== expected.executionId ||
    matrix.environment !== "production" ||
    matrix.stageBExecutionEvidenceSha256 !==
      expected.stageBExecutionEvidenceSha256 ||
    matrix.subjectDigest !== expected.subjectDigest ||
    matrix.subjectCount !== PRODUCTION_DIRECT_MATRIX_CELL_COUNT ||
    matrix.nodeCount !== NODES.length ||
    matrix.phaseCount !== PRODUCTION_DIRECT_MATRIX_PHASES.length ||
    matrix.roleCount !== ROLES.length ||
    matrix.surfaceCount !== PRODUCTION_DIRECT_MATRIX_SURFACES.length ||
    matrix.cellCount !== PRODUCTION_DIRECT_MATRIX_CELL_COUNT ||
    matrix.ordinaryUserNegativePassed !== true ||
    matrix.rootBreakGlassPassed !== true ||
    matrix.permissionUnionAppliedCount !== 0 ||
    matrix.fallbackAppliedCount !== 0 ||
    matrix.mutationCount !== 0 ||
    matrix.unexpected5xxCount !== 0
  )
    return reject();
  const capturedAtCandidate = matrix.capturedAt;
  if (!isExactIsoInstant(capturedAtCandidate)) return reject();
  const capturedAt = capturedAtCandidate;
  const roleSubjectDigestCandidate = matrix.roleSubjectDigests;
  if (
    !isPlainRecord(roleSubjectDigestCandidate) ||
    !hasExactObjectKeys(roleSubjectDigestCandidate, ROLES)
  )
    return reject();
  const roleSubjectDigestRecord = roleSubjectDigestCandidate;
  const roleSubjectDigests: Record<RunnerRole, string> = {
    user: "",
    manager: "",
    admin: "",
    root: "",
  };
  for (const role of ROLES) {
    const digest = roleSubjectDigestRecord[role];
    if (
      typeof digest !== "string" ||
      !/^[a-f0-9]{64}$/.test(digest) ||
      digest === "0".repeat(64)
    )
      return reject();
    roleSubjectDigests[role] = digest;
  }
  const digests = ROLES.map((role) => roleSubjectDigests[role]);
  if (new Set(digests).size !== ROLES.length) return reject();
  const expectedNodePhases = NODES.flatMap((node) =>
    PRODUCTION_DIRECT_MATRIX_PHASES.map((phase, index) => ({
      node,
      ordinal: index + 1,
      phase,
    }))
  );
  const nodePhases = matrix.nodePhases;
  if (
    !Array.isArray(nodePhases) ||
    nodePhases.length !== expectedNodePhases.length
  )
    return reject();
  const nodePhaseRefs: string[] = [];
  const nodePhaseTimes: number[] = [];
  for (let index = 0; index < expectedNodePhases.length; index += 1) {
    const entry = nodePhases[index];
    const wanted = expectedNodePhases[index];
    if (
      !isPlainRecord(entry) ||
      !hasExactObjectKeys(entry, PRODUCTION_DIRECT_MATRIX_NODE_PHASE_KEYS) ||
      entry.node !== wanted.node ||
      entry.phase !== wanted.phase ||
      entry.ordinal !== wanted.ordinal ||
      !isExactIsoInstant(entry.observedAt) ||
      typeof entry.expectedBackendPublishSha !== "string" ||
      !/^[a-f0-9]{40}$/.test(entry.expectedBackendPublishSha) ||
      entry.observedBackendPublishSha !== entry.expectedBackendPublishSha ||
      entry.backendPublishShaExact !== true ||
      typeof entry.expectedIdentityPublishSha !== "string" ||
      !/^[a-f0-9]{40}$/.test(entry.expectedIdentityPublishSha) ||
      entry.observedIdentityPublishSha !== entry.expectedIdentityPublishSha ||
      entry.identityPublishShaExact !== true ||
      entry.sourceExact !== true ||
      entry.runtimeExact !== true ||
      entry.backendHealthy !== true ||
      entry.identityHealthy !== true ||
      entry.publicHealthPassed !== true ||
      entry.authzMode !== (wanted.phase === "hit" ? "shadow" : "legacy") ||
      entry.backendRouteIntegrationEnabled !== (wanted.phase === "hit") ||
      entry.responseProvider !== "legacy" ||
      entry.legacyResponseParityMatched !== true ||
      entry.permissionUnionAppliedCount !== 0 ||
      entry.fallbackAppliedCount !== 0 ||
      entry.mutationCount !== 0 ||
      entry.unexpected5xxCount !== 0 ||
      !isProductionMatrixEvidenceRef(entry.evidenceRef)
    )
      return reject();
    nodePhaseRefs.push(entry.evidenceRef);
    nodePhaseTimes.push(Date.parse(entry.observedAt));
  }
  if (new Set(nodePhaseRefs).size !== nodePhaseRefs.length) return reject();
  for (let nodeIndex = 0; nodeIndex < NODES.length; nodeIndex += 1) {
    const first = nodeIndex * PRODUCTION_DIRECT_MATRIX_PHASES.length;
    const times = nodePhaseTimes.slice(
      first,
      first + PRODUCTION_DIRECT_MATRIX_PHASES.length
    );
    if (times.some((time, index) => index > 0 && time <= times[index - 1])) {
      return reject();
    }
  }
  if (Date.parse(capturedAt) < Math.max(...nodePhaseTimes)) return reject();
  const subjects = NODES.flatMap((node) =>
    PRODUCTION_DIRECT_MATRIX_PHASES.flatMap((phase) =>
      ROLES.flatMap((role) =>
        PRODUCTION_DIRECT_MATRIX_SURFACES.map((surface) => ({
          node,
          phase,
          role,
          surface,
        }))
      )
    )
  );
  const cells = matrix.cells;
  if (!Array.isArray(cells) || cells.length !== subjects.length) {
    return reject();
  }
  const cellRefs: string[] = [];
  for (let index = 0; index < subjects.length; index += 1) {
    const cell = cells[index];
    const subject = subjects[index];
    const ordinaryNegative =
      subject.role === "user" &&
      PRODUCTION_DIRECT_MATRIX_ORDINARY_USER_DENIED_SURFACES.has(
        subject.surface
      );
    if (
      !isPlainRecord(cell) ||
      !hasExactObjectKeys(cell, PRODUCTION_DIRECT_MATRIX_CELL_KEYS) ||
      cell.node !== subject.node ||
      cell.phase !== subject.phase ||
      cell.role !== subject.role ||
      cell.surface !== subject.surface ||
      cell.ledgerKey !==
        `${subject.node}|${subject.phase}|${subject.role}|${subject.surface}` ||
      cell.roleSubjectDigest !== roleSubjectDigests[subject.role] ||
      cell.currentProduction !== true ||
      cell.directObserved !== true ||
      cell.fresh !== true ||
      cell.expectedDecisionMatched !== true ||
      cell.legacyResponseParityMatched !== true ||
      cell.ordinaryUserPrivilegedDenied !== ordinaryNegative ||
      cell.rootBreakGlassPreserved !== (subject.role === "root") ||
      cell.permissionUnionApplied !== false ||
      cell.fallbackApplied !== false ||
      cell.mutationCount !== 0 ||
      cell.unexpected5xxCount !== 0 ||
      !isProductionMatrixEvidenceRef(cell.evidenceRef)
    )
      return reject();
    cellRefs.push(cell.evidenceRef);
  }
  if (
    new Set(cellRefs).size !== cellRefs.length ||
    new Set([...nodePhaseRefs, ...cellRefs]).size !==
      nodePhaseRefs.length + cellRefs.length ||
    !bytesEqual(raw, encodeAsciiSortedCanonicalJson(matrix))
  )
    return reject();
  return Object.freeze({
    approvalRef: expected.approvalRef,
    capturedAt,
    executionId: expected.executionId,
    roleSubjectDigests: Object.freeze({ ...roleSubjectDigests }),
    stageBExecutionEvidenceSha256: expected.stageBExecutionEvidenceSha256,
    subjectDigest: expected.subjectDigest,
  });
}

export function isUint8ArrayBytes(value: unknown): value is Uint8Array {
  return Object.prototype.toString.call(value) === "[object Uint8Array]";
}

/** Accepts only the exact, already-canonical raw Stage B approval artifact. */
export function parseStageBExecutionEvidence(
  raw: Uint8Array,
  nowMs: number
): StageBExecutionEvidence {
  if (
    !isUint8ArrayBytes(raw) ||
    raw.byteLength === 0 ||
    raw.byteLength > STAGE_B_EXECUTION_EVIDENCE_MAX_BYTES
  ) {
    throw new Error("TASK51_STAGE_B_EXECUTION_EVIDENCE_REJECTED");
  }
  let parsed: unknown;
  try {
    parsed = JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(raw));
  } catch {
    throw new Error("TASK51_STAGE_B_EXECUTION_EVIDENCE_REJECTED");
  }
  if (
    !isPlainRecord(parsed) ||
    !hasExactObjectKeys(parsed, STAGE_B_EXECUTION_EVIDENCE_KEYS) ||
    parsed.schema !== STAGE_B_EXECUTION_EVIDENCE_SCHEMA ||
    parsed.protocol !== PROTOCOL ||
    !matchesPattern(parsed.approvalRef, STAGE_B_APPROVAL_PATTERN) ||
    !matchesPattern(parsed.executionId, STAGE_B_EXECUTION_PATTERN) ||
    !matchesPattern(parsed.stageAApprovalRef, STAGE_A_APPROVAL_PATTERN) ||
    typeof parsed.stageACoordinatorServerReleaseEvidenceSha256 !== "string" ||
    !/^[a-f0-9]{64}$/.test(
      parsed.stageACoordinatorServerReleaseEvidenceSha256
    ) ||
    typeof parsed.stageANetworkAttestorReleaseEvidenceSha256 !== "string" ||
    !/^[a-f0-9]{64}$/.test(parsed.stageANetworkAttestorReleaseEvidenceSha256) ||
    typeof parsed.stageAReleaseEvidenceSha256 !== "string" ||
    !/^[a-f0-9]{64}$/.test(parsed.stageAReleaseEvidenceSha256) ||
    parsed.coordinatorOrigin !== STAGE_B_COORDINATOR_ORIGIN ||
    typeof parsed.coordinatorServerPublishSha !== "string" ||
    !/^[a-f0-9]{40}$/.test(parsed.coordinatorServerPublishSha) ||
    typeof parsed.claimCapabilitySha256 !== "string" ||
    !/^[a-f0-9]{64}$/.test(parsed.claimCapabilitySha256) ||
    parsed.status !== "APPROVED" ||
    parsed.oneShot !== true ||
    parsed.currentWindowOnly !== true ||
    parsed.authorizedControlPostCount !== 1 ||
    parsed.authorizedLoginCount !== 4 ||
    parsed.authorizedLogoutCount !== 4 ||
    parsed.authorizedLogicalGetCount !== 56 ||
    parsed.productionDirectMatrixSchema !== PRODUCTION_DIRECT_MATRIX_SCHEMA ||
    !isProductionMatrixEvidenceRef(parsed.productionDirectMatrixEvidenceRef) ||
    parsed.productionDirectMatrixAuthorizedCellCount !==
      PRODUCTION_DIRECT_MATRIX_CELL_COUNT ||
    typeof parsed.productionDirectMatrixSubjectDigest !== "string" ||
    !/^[a-f0-9]{64}$/.test(parsed.productionDirectMatrixSubjectDigest) ||
    parsed.productionDirectMatrixSubjectDigest === "0".repeat(64) ||
    !isExactIsoInstant(parsed.issuedAt) ||
    !isExactIsoInstant(parsed.expiresAt)
  ) {
    throw new Error("TASK51_STAGE_B_EXECUTION_EVIDENCE_REJECTED");
  }
  const issuedAtMs = Date.parse(parsed.issuedAt);
  const expiresAtMs = Date.parse(parsed.expiresAt);
  const windowDurationMs = expiresAtMs - issuedAtMs;
  if (
    issuedAtMs > nowMs ||
    nowMs >= expiresAtMs ||
    expiresAtMs - nowMs < STAGE_B_MIN_REMAINING_EXECUTION_MS ||
    windowDurationMs < 35 * 60 * 1_000 ||
    windowDurationMs > 2 * 60 * 60 * 1_000
  ) {
    throw new Error("TASK51_STAGE_B_EXECUTION_EVIDENCE_REJECTED");
  }
  const exact = Object.freeze({
    approvalRef: parsed.approvalRef,
    authorizedControlPostCount: 1,
    authorizedLogicalGetCount: 56,
    authorizedLoginCount: 4,
    authorizedLogoutCount: 4,
    claimCapabilitySha256: parsed.claimCapabilitySha256,
    coordinatorOrigin: STAGE_B_COORDINATOR_ORIGIN,
    coordinatorServerPublishSha: parsed.coordinatorServerPublishSha,
    currentWindowOnly: true,
    executionId: parsed.executionId,
    expiresAt: parsed.expiresAt,
    issuedAt: parsed.issuedAt,
    oneShot: true,
    productionDirectMatrixAuthorizedCellCount:
      PRODUCTION_DIRECT_MATRIX_CELL_COUNT,
    productionDirectMatrixEvidenceRef: parsed.productionDirectMatrixEvidenceRef,
    productionDirectMatrixSchema: PRODUCTION_DIRECT_MATRIX_SCHEMA,
    productionDirectMatrixSubjectDigest:
      parsed.productionDirectMatrixSubjectDigest,
    protocol: PROTOCOL,
    schema: STAGE_B_EXECUTION_EVIDENCE_SCHEMA,
    stageAApprovalRef: parsed.stageAApprovalRef,
    stageACoordinatorServerReleaseEvidenceSha256:
      parsed.stageACoordinatorServerReleaseEvidenceSha256,
    stageANetworkAttestorReleaseEvidenceSha256:
      parsed.stageANetworkAttestorReleaseEvidenceSha256,
    stageAReleaseEvidenceSha256: parsed.stageAReleaseEvidenceSha256,
    status: "APPROVED",
  });
  if (!bytesEqual(raw, encodeAsciiSortedCanonicalJson(exact))) {
    throw new Error("TASK51_STAGE_B_EXECUTION_EVIDENCE_REJECTED");
  }
  return exact;
}

/**
 * Accepts only the canonical safe receipt returned by the single authoritative
 * coordinator. The raw claim capability never enters this parser or the page.
 */
export function parseStageBGlobalClaimReceipt(
  raw: Uint8Array,
  stageB: StageBExecutionEvidence,
  stageBExecutionEvidenceSha256: string,
  nowMs: number
): StageBGlobalClaimReceipt {
  if (
    !isUint8ArrayBytes(raw) ||
    raw.byteLength === 0 ||
    raw.byteLength > STAGE_B_GLOBAL_CLAIM_RECEIPT_MAX_BYTES ||
    !/^[a-f0-9]{64}$/.test(stageBExecutionEvidenceSha256)
  ) {
    throw new Error("TASK51_STAGE_B_GLOBAL_CLAIM_RECEIPT_REJECTED");
  }

  let parsed: unknown;
  try {
    parsed = JSON.parse(new TextDecoder("utf-8", { fatal: true }).decode(raw));
  } catch {
    throw new Error("TASK51_STAGE_B_GLOBAL_CLAIM_RECEIPT_REJECTED");
  }

  if (
    !isPlainRecord(parsed) ||
    !hasExactObjectKeys(parsed, STAGE_B_GLOBAL_CLAIM_RECEIPT_KEYS) ||
    parsed.schema !== STAGE_B_GLOBAL_CLAIM_RECEIPT_SCHEMA ||
    parsed.approvalRef !== stageB.approvalRef ||
    parsed.executionId !== stageB.executionId ||
    parsed.state !== "CLAIMED" ||
    parsed.globalExactOneClaimed !== true ||
    parsed.claimCount !== 1 ||
    parsed.expiresAt !== stageB.expiresAt ||
    parsed.stageBExecutionEvidenceSha256 !== stageBExecutionEvidenceSha256 ||
    parsed.coordinatorOrigin !== STAGE_B_COORDINATOR_ORIGIN ||
    parsed.coordinatorOrigin !== stageB.coordinatorOrigin ||
    parsed.coordinatorServerPublishSha !== stageB.coordinatorServerPublishSha ||
    !isExactIsoInstant(parsed.claimedAt) ||
    !isExactIsoInstant(parsed.expiresAt)
  ) {
    throw new Error("TASK51_STAGE_B_GLOBAL_CLAIM_RECEIPT_REJECTED");
  }

  const issuedAtMs = Date.parse(stageB.issuedAt);
  const claimedAtMs = Date.parse(parsed.claimedAt);
  const expiresAtMs = Date.parse(parsed.expiresAt);
  if (
    claimedAtMs < issuedAtMs ||
    claimedAtMs > nowMs + CLOCK_SKEW_MS ||
    claimedAtMs >= expiresAtMs ||
    nowMs >= expiresAtMs ||
    expiresAtMs - nowMs < STAGE_B_MIN_REMAINING_EXECUTION_MS
  ) {
    throw new Error("TASK51_STAGE_B_GLOBAL_CLAIM_RECEIPT_REJECTED");
  }

  const exact = Object.freeze({
    approvalRef: stageB.approvalRef,
    claimCount: 1,
    claimedAt: parsed.claimedAt,
    coordinatorOrigin: STAGE_B_COORDINATOR_ORIGIN,
    coordinatorServerPublishSha: stageB.coordinatorServerPublishSha,
    executionId: stageB.executionId,
    expiresAt: stageB.expiresAt,
    globalExactOneClaimed: true,
    schema: STAGE_B_GLOBAL_CLAIM_RECEIPT_SCHEMA,
    stageBExecutionEvidenceSha256,
    state: "CLAIMED",
  });
  if (!bytesEqual(raw, encodeAsciiSortedCanonicalJson(exact))) {
    throw new Error("TASK51_STAGE_B_GLOBAL_CLAIM_RECEIPT_REJECTED");
  }
  return exact;
}

export function task51SafeCellResultPasses(cell: SafeCellResult): boolean {
  const expectedStatus =
    cell.path !== "/v1/organization/list" ||
    cell.role === "admin" ||
    cell.role === "root"
      ? 200
      : 403;
  const identityBearing = cell.path !== "/v1/organization/list";
  const expectedCrossNodeIdentity = identityBearing
    ? cell.phase === "readiness" && cell.node === "xrteeth"
      ? null
      : true
    : null;

  return (
    /^[a-f0-9]{64}$/.test(cell.roleSubjectDigest) &&
    cell.roleSubjectDigest !== "0".repeat(64) &&
    cell.httpStatus === expectedStatus &&
    cell.transportPassed === true &&
    cell.schemaPassed === true &&
    cell.expectedDecisionMatched === true &&
    cell.baselineParityMatched === (cell.phase === "shadow" ? true : null) &&
    cell.roleExact === (identityBearing ? true : null) &&
    cell.crossNodeIdentityMatched === expectedCrossNodeIdentity
  );
}

function isExactSafeCellResult(
  value: unknown,
  expectedIndex: number
): value is SafeCellResult {
  if (
    !isPlainRecord(value) ||
    !hasExactObjectKeys(value, SAFE_CELL_RESULT_KEYS)
  ) {
    return false;
  }
  const expected = EVIDENCE_LEDGER[expectedIndex];
  if (!expected) return false;
  const exactShape =
    value.ledgerKey === expected.key &&
    value.phase === expected.phase &&
    value.node === expected.node &&
    value.role === expected.role &&
    typeof value.roleSubjectDigest === "string" &&
    /^[a-f0-9]{64}$/.test(value.roleSubjectDigest) &&
    value.roleSubjectDigest !== "0".repeat(64) &&
    value.path === expected.path &&
    Number.isInteger(value.httpStatus) &&
    typeof value.transportPassed === "boolean" &&
    typeof value.schemaPassed === "boolean" &&
    typeof value.expectedDecisionMatched === "boolean" &&
    (value.baselineParityMatched === null ||
      typeof value.baselineParityMatched === "boolean") &&
    (value.roleExact === null || typeof value.roleExact === "boolean") &&
    (value.crossNodeIdentityMatched === null ||
      typeof value.crossNodeIdentityMatched === "boolean");
  return (
    exactShape && task51SafeCellResultPasses(value as unknown as SafeCellResult)
  );
}

export function isExactTask51RunnerFragment(
  value: unknown
): value is Task51RunnerFragment {
  if (!isPlainRecord(value) || !hasExactObjectKeys(value, FRAGMENT_KEYS)) {
    return false;
  }
  const safeCellCandidates = value.safeCellResults;
  const countsValue = value.counts;
  const flagsValue = value.flags;
  if (
    value.schema !== RUNNER_FRAGMENT_SCHEMA ||
    value.protocol !== PROTOCOL ||
    !matchesPattern(value.approvalRef, STAGE_B_APPROVAL_PATTERN) ||
    !matchesPattern(value.executionId, STAGE_B_EXECUTION_PATTERN) ||
    typeof value.stageBExecutionEvidenceSha256 !== "string" ||
    !/^[a-f0-9]{64}$/.test(value.stageBExecutionEvidenceSha256) ||
    typeof value.stageBGlobalClaimReceiptSha256 !== "string" ||
    !/^[a-f0-9]{64}$/.test(value.stageBGlobalClaimReceiptSha256) ||
    !isProductionMatrixEvidenceRef(value.productionDirectMatrixEvidenceRef) ||
    typeof value.productionDirectMatrixEvidenceSha256 !== "string" ||
    !/^[a-f0-9]{64}$/.test(value.productionDirectMatrixEvidenceSha256) ||
    value.productionDirectMatrixEvidenceSha256 === "0".repeat(64) ||
    typeof value.productionDirectMatrixSubjectDigest !== "string" ||
    !/^[a-f0-9]{64}$/.test(value.productionDirectMatrixSubjectDigest) ||
    value.productionDirectMatrixSubjectDigest === "0".repeat(64) ||
    !isExactIsoInstant(value.stageBClaimedAt) ||
    !isExactIsoInstant(value.exportedAt) ||
    Date.parse(value.stageBClaimedAt) > Date.parse(value.exportedAt) ||
    !Array.isArray(safeCellCandidates) ||
    safeCellCandidates.length !== 56 ||
    !isPlainRecord(countsValue) ||
    !hasExactObjectKeys(countsValue, FRAGMENT_COUNT_KEYS) ||
    !isPlainRecord(flagsValue) ||
    !hasExactObjectKeys(flagsValue, FRAGMENT_FLAG_KEYS)
  ) {
    return false;
  }
  const safeCellResults: SafeCellResult[] = [];
  for (let index = 0; index < safeCellCandidates.length; index += 1) {
    const candidate = safeCellCandidates[index];
    if (!isExactSafeCellResult(candidate, index)) return false;
    safeCellResults.push(candidate);
  }
  const counts = countsValue;
  const flags = flagsValue;
  const roleSubjectDigests = Object.fromEntries(
    ROLES.map((role) => [
      role,
      safeCellResults.find((cell) => cell.role === role)?.roleSubjectDigest,
    ])
  );
  const exactRoleSubjectDigests = ROLES.map((role) => roleSubjectDigests[role]);
  return (
    exactRoleSubjectDigests.every(
      (digest) => typeof digest === "string" && /^[a-f0-9]{64}$/.test(digest)
    ) &&
    new Set(exactRoleSubjectDigests).size === ROLES.length &&
    safeCellResults.every(
      (cell) => cell.roleSubjectDigest === roleSubjectDigests[cell.role]
    ) &&
    counts.baselineCellCount === 24 &&
    counts.burnedLogicalGetCount === 56 &&
    counts.captureCount === 4 &&
    counts.completedLogicalGetCount === 56 &&
    counts.duplicateCellCount === 0 &&
    counts.expectedLogicalGetCount === 56 &&
    counts.failedCellCount === 0 &&
    counts.maxInFlightGetCount === 1 &&
    counts.personalDataFindingCount === 0 &&
    counts.readinessCellCount === 8 &&
    counts.retryCount === 0 &&
    counts.shadowCellCount === 24 &&
    counts.tmrppShadowCellCount === 12 &&
    counts.unknownCellCount === 0 &&
    counts.unsafeFieldCount === 0 &&
    counts.xrteethShadowCellCount === 12 &&
    flags.captureAcceptanceImpliesSuccessfulRevoke === true &&
    flags.cleared === true &&
    flags.completed === true &&
    flags.externalGatesPassedBeforeCapture === true &&
    flags.ordinaryUserNegativePassed === true &&
    flags.responseMaterialPersisted === false &&
    flags.responseMaterialPrintedOrLogged === false &&
    flags.rootBreakGlassPassed === true &&
    flags.safeOutputOnly === true &&
    flags.strictlySerial === true &&
    flags.workerReferencesCleared === true
  );
}

export function encodeTask51RunnerFragment(
  fragment: Task51RunnerFragment
): Uint8Array {
  if (!isExactTask51RunnerFragment(fragment) || !isSafeRunnerOutput(fragment)) {
    throw new Error("TASK51_RUNNER_FRAGMENT_REJECTED");
  }
  return encodeAsciiSortedCanonicalJson(fragment);
}

export type RunnerSafeEvent =
  | Readonly<{
      protocol: typeof PROTOCOL;
      type: "state";
      state: RunnerState;
    }>
  | Readonly<{
      protocol: typeof PROTOCOL;
      type: "capture-result";
      role: RunnerRole;
      loginHttpStatus: number;
      logoutHttpStatus: number;
      roleExact: boolean;
      ttlSufficient: boolean;
    }>
  | Readonly<{
      protocol: typeof PROTOCOL;
      type: "cell-result";
      cell: SafeCellResult;
    }>
  | Readonly<{
      protocol: typeof PROTOCOL;
      type: "progress";
      burnedCells: number;
      totalCells: 56;
    }>
  | Readonly<{
      protocol: typeof PROTOCOL;
      type: "external-gates";
      passed: boolean;
    }>
  | Readonly<{
      protocol: typeof PROTOCOL;
      type: "failure";
      code: RunnerFailureCode;
      state: "FAILED_TERMINAL";
    }>
  | Readonly<{
      protocol: typeof PROTOCOL;
      type: "cleared";
      state: "CLEARED";
      workerReferencesCleared: boolean;
    }>;

const FORBIDDEN_OUTPUT_KEY_PARTS = [
  "password",
  "passphrase",
  "token",
  "bearer",
  "authorization",
  "cookie",
  "credential",
  "secret",
  "username",
  "profile",
  "subject",
  "digest",
  "rawbody",
  "responsebody",
  "requestbody",
  "jwt",
] as const;
const SAFE_OPAQUE_DIGEST_OUTPUT_KEYS = new Set([
  "rolesubjectdigest",
  "productiondirectmatrixsubjectdigest",
]);

const MAX_SAFE_OUTPUT_DEPTH = 8;
const MAX_SAFE_OUTPUT_STRING_LENGTH = 512;

function normalizedOutputKey(key: string): string {
  return key.toLowerCase().replace(/[^a-z0-9]/g, "");
}

function hasSensitiveStringShape(value: string): boolean {
  if (value.length > MAX_SAFE_OUTPUT_STRING_LENGTH) return true;
  if (/^(?:Bearer|Basic)\s+/i.test(value)) return true;
  // Shape-only rejection. No JWT parsing or payload inspection occurs here.
  if (/^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$/.test(value)) {
    return true;
  }
  return false;
}

/**
 * Runtime backstop for anything posted toward the page/reporting realm.
 * It intentionally accepts only JSON-safe data and rejects secret-bearing
 * names/shapes, binary bodies, exotic prototypes and cycles.
 */
export function isSafeRunnerOutput(value: unknown): boolean {
  const seen = new Set<object>();

  const visit = (candidate: unknown, depth: number): boolean => {
    if (depth > MAX_SAFE_OUTPUT_DEPTH) return false;
    if (candidate === null || typeof candidate === "boolean") return true;
    if (typeof candidate === "number") return Number.isFinite(candidate);
    if (typeof candidate === "string")
      return !hasSensitiveStringShape(candidate);
    if (typeof candidate !== "object") return false;
    if (seen.has(candidate)) return false;
    seen.add(candidate);

    if (Array.isArray(candidate)) {
      return candidate.every((entry) => visit(entry, depth + 1));
    }
    if (!isPlainRecord(candidate)) return false;

    return Object.entries(candidate).every(([key, entry]) => {
      const normalized = normalizedOutputKey(key);
      if (
        !SAFE_OPAQUE_DIGEST_OUTPUT_KEYS.has(normalized) &&
        FORBIDDEN_OUTPUT_KEY_PARTS.some((part) => normalized.includes(part))
      ) {
        return false;
      }
      return visit(entry, depth + 1);
    });
  };

  return visit(value, 0);
}

export function assertSafeRunnerOutput(
  value: unknown
): asserts value is RunnerSafeEvent {
  if (!isSafeRunnerOutput(value)) {
    throw new Error("TASK51_UNSAFE_RUNNER_OUTPUT");
  }
}
