services:
  vue3:
    build: .
    environment:
      - APP_API_1_URL=https://api.your-domain.com
      - APP_API_2_URL=https://backup-api.your-domain.com
      - APP_DOMAIN_1_URL=https://domain-info.your-domain.com
      - APP_DOMAIN_2_URL=https://backup-domain-info.your-domain.com
      - APP_DOC_API_URL=https://docs.your-domain.com/wp-json/wp/v2
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "8088:80"
