services:
  vue3-dev:
    build:
      context: .
      target: dev
    container_name: vue3-dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - VITE_APP_API_URL=https://api.xrteeth.com
      - VITE_APP_BACKUP_API_URL=https://api.tmrpp.com
      - VITE_APP_DOMAIN_INFO_API_URL=https://domain.xrteeth.com
      - VITE_APP_BACKUP_DOMAIN_INFO_API_URL=https://domain.tmrpp.com
      - NGINX_PORT=80
      - VITE_APP_PORT=3000
    command: pnpm run dev --host
