// 情感类型映射表（中文显示 -> 英文参数）
export const emotionMap: Record<string, string> = {
  中性: "neutral",
  悲伤: "sad",
  高兴: "happy",
  生气: "angry",
  恐惧: "fear",
  新闻: "news",
  故事: "story",
  广播: "radio",
  诗歌: "poetry",
  客服: "call",
  撒娇: "sajiao",
  厌恶: "disgusted",
  震惊: "amaze",
  平静: "peaceful",
  兴奋: "exciting",
  傲娇: "aojiao",
  解说: "jieshuo",
};

// 英文参数 -> 中文显示的反向映射
export const reverseEmotionMap: Record<string, string> = Object.entries(
  emotionMap
).reduce(
  (acc, [key, value]) => {
    acc[value] = key;
    return acc;
  },
  {} as Record<string, string>
);

// 音色类型定义
export interface VoiceType {
  label: string;
  value: number;
  emotions: string[];
  type: string;
  scene: string;
  language: string;
  sampleRate: string[];
}

// 可用音色列表
export const availableVoices: VoiceType[] = [
  // 精品音色
  {
    label: "智逍遥，阅读男声(精品)",
    value: 100510000,
    emotions: ["中性"],
    type: "精品音色",
    scene: "阅读男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智瑜，情感女声(精品)",
    value: 101001,
    emotions: ["中性"],
    type: "精品音色",
    scene: "情感女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智聆，通用女声(精品)",
    value: 101002,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智美，客服女声(精品)",
    value: 101003,
    emotions: ["中性"],
    type: "精品音色",
    scene: "客服女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智云，通用男声(精品)",
    value: 101004,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智莉，通用女声(精品)",
    value: 101005,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智言，助手女声(精品)",
    value: 101006,
    emotions: ["中性"],
    type: "精品音色",
    scene: "助手女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智琪，客服女声(精品)",
    value: 101008,
    emotions: ["中性"],
    type: "精品音色",
    scene: "客服女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智芸，知性女声(精品)",
    value: 101009,
    emotions: ["中性"],
    type: "精品音色",
    scene: "知性女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智华，通用男声(精品)",
    value: 101010,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智燕，新闻女声(精品)",
    value: 101011,
    emotions: ["中性"],
    type: "精品音色",
    scene: "新闻女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智丹，新闻女声(精品)",
    value: 101012,
    emotions: ["中性"],
    type: "精品音色",
    scene: "新闻女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智辉，新闻男声(精品)",
    value: 101013,
    emotions: ["中性"],
    type: "精品音色",
    scene: "新闻男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智宁，新闻男声(精品)",
    value: 101014,
    emotions: ["中性"],
    type: "精品音色",
    scene: "新闻男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智萌，男童声(精品)",
    value: 101015,
    emotions: ["中性"],
    type: "精品音色",
    scene: "男童声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智甜，女童声(精品)",
    value: 101016,
    emotions: ["中性"],
    type: "精品音色",
    scene: "女童声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智蓉，情感女声(精品)",
    value: 101017,
    emotions: ["中性"],
    type: "精品音色",
    scene: "情感女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智靖，情感男声(精品)",
    value: 101018,
    emotions: ["中性"],
    type: "精品音色",
    scene: "情感男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智彤，粤语女声(精品)",
    value: 101019,
    emotions: ["中性"],
    type: "精品音色",
    scene: "粤语女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智刚，新闻男声(精品)",
    value: 101020,
    emotions: ["中性"],
    type: "精品音色",
    scene: "新闻男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智瑞，新闻男声(精品)",
    value: 101021,
    emotions: ["中性"],
    type: "精品音色",
    scene: "新闻男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智虹，新闻女声(精品)",
    value: 101022,
    emotions: ["中性"],
    type: "精品音色",
    scene: "新闻女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智萱，聊天女声(精品)",
    value: 101023,
    emotions: ["中性"],
    type: "精品音色",
    scene: "聊天女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智皓，聊天男声(精品)",
    value: 101024,
    emotions: ["中性"],
    type: "精品音色",
    scene: "聊天男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智薇，聊天女声(精品)",
    value: 101025,
    emotions: ["中性"],
    type: "精品音色",
    scene: "聊天女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智希，通用女声(精品)",
    value: 101026,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智梅，通用女声(精品)",
    value: 101027,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智洁，通用女声(精品)",
    value: 101028,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智凯，通用男声(精品)",
    value: 101029,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智柯，通用男声(精品)",
    value: 101030,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智奎，通用男声(精品)",
    value: 101031,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智芳，通用女声(精品)",
    value: 101032,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智蓓，客服女声(精品)",
    value: 101033,
    emotions: ["中性"],
    type: "精品音色",
    scene: "客服女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智佳，客服女声(精品)",
    value: 101081,
    emotions: ["中性"],
    type: "精品音色",
    scene: "客服女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智英，客服女声(精品)",
    value: 101080,
    emotions: ["中性"],
    type: "精品音色",
    scene: "客服女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智莲，通用女声(精品)",
    value: 101034,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智依，通用女声(精品)",
    value: 101035,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智川，四川女声(精品)",
    value: 101040,
    emotions: ["中性"],
    type: "精品音色",
    scene: "四川女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "WeJack，英文男声(精品)",
    value: 101050,
    emotions: ["中性"],
    type: "精品音色",
    scene: "英文男声",
    language: "英文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "WeRose，英文女声(精品)",
    value: 101051,
    emotions: ["中性"],
    type: "精品音色",
    scene: "英文女声",
    language: "英文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智味，通用男声(精品)",
    value: 101052,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智方，通用男声(精品)",
    value: 101053,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智友，通用男声(精品)",
    value: 101054,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智付，通用女声(精品)",
    value: 101055,
    emotions: ["中性"],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智林，东北男声(精品)",
    value: 101056,
    emotions: ["中性"],
    type: "精品音色",
    scene: "东北男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智美子，日语女声(精品)",
    value: 101057,
    emotions: ["中性"],
    type: "精品音色",
    scene: "日语女声",
    language: "日文",
    sampleRate: ["8k", "16k"],
  },

  // 多情感音色
  {
    label: "爱小广，通用男声(多情感)",
    value: 301000,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小栋，通用男声(多情感)",
    value: 301001,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小海，通用男声(多情感)",
    value: 301002,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小霞，通用女声(多情感)",
    value: 301003,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小玲，通用女声(多情感)",
    value: 301004,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小章，通用男声(多情感)",
    value: 301005,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小峰，通用男声(多情感)",
    value: 301006,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小亮，通用男声(多情感)",
    value: 301007,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小博，通用男声(多情感)",
    value: 301008,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小芸，通用女声(多情感)",
    value: 301009,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小秋，通用女声(多情感)",
    value: 301010,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小芳，通用女声(多情感)",
    value: 301011,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小琴，通用女声(多情感)",
    value: 301012,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小康，通用男声(多情感)",
    value: 301013,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小辉，通用男声(多情感)",
    value: 301014,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小璐，通用女声(多情感)",
    value: 301015,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小阳，通用男声(多情感)",
    value: 301016,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小泉，通用男声(多情感)",
    value: 301017,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小昆，通用男声(多情感)",
    value: 301018,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小诚，通用男声(多情感)",
    value: 301019,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小岚，通用女声(多情感)",
    value: 301020,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小茹，通用女声(多情感)",
    value: 301021,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小蓉，通用女声(多情感)",
    value: 301022,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小燕，通用女声(多情感)",
    value: 301023,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小莲，通用女声(多情感)",
    value: 301024,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小武，通用男声(多情感)",
    value: 301025,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小雪，通用女声(多情感)",
    value: 301026,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小媛，通用女声(多情感)",
    value: 301027,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小娴，通用女声(多情感)",
    value: 301028,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小涛，通用男声(多情感)",
    value: 301029,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "新闻",
      "故事",
      "广播",
      "诗歌",
      "客服",
    ],
    type: "精品音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "爱小溪，对话女声(多情感)",
    value: 301030,
    emotions: ["中性"],
    type: "精品音色",
    scene: "对话女声",
    language: "中文",
    sampleRate: ["8k", "16k", "24k"],
  },
  {
    label: "爱小树，对话男声(多情感)",
    value: 301031,
    emotions: ["中性", "高兴", "生气", "悲伤", "恐惧", "震惊", "撒娇", "厌恶"],
    type: "精品音色",
    scene: "对话男声",
    language: "中文",
    sampleRate: ["8k", "16k", "24k"],
  },
  {
    label: "爱小荷，对话女声(多情感)",
    value: 301032,
    emotions: ["中性", "高兴", "生气", "悲伤", "恐惧", "震惊", "撒娇", "厌恶"],
    type: "精品音色",
    scene: "对话女声",
    language: "中文",
    sampleRate: ["8k", "16k", "24k"],
  },
  {
    label: "爱小叶，对话女声(多情感)",
    value: 301033,
    emotions: ["中性", "高兴", "生气", "悲伤", "恐惧", "震惊", "撒娇", "厌恶"],
    type: "精品音色",
    scene: "对话女声",
    language: "中文",
    sampleRate: ["8k", "16k", "24k"],
  },
  {
    label: "爱小杭，对话男声(多情感)",
    value: 301034,
    emotions: ["中性", "高兴", "生气", "悲伤", "恐惧", "震惊", "撒娇", "厌恶"],
    type: "精品音色",
    scene: "对话男声",
    language: "中文",
    sampleRate: ["8k", "16k", "24k"],
  },
  {
    label: "爱小梅，对话女声(多情感)",
    value: 301035,
    emotions: ["中性", "高兴", "生气", "悲伤", "恐惧", "震惊", "撒娇", "厌恶"],
    type: "精品音色",
    scene: "对话女声",
    language: "中文",
    sampleRate: ["8k", "16k", "24k"],
  },
  {
    label: "爱小柯，对话男声(多情感)",
    value: 301036,
    emotions: ["中性", "高兴", "生气", "悲伤", "恐惧", "震惊", "撒娇", "厌恶"],
    type: "精品音色",
    scene: "对话男声",
    language: "中文",
    sampleRate: ["8k", "16k", "24k"],
  },
  {
    label: "爱小静，对话女声(多情感)",
    value: 301037,
    emotions: ["中性"],
    type: "精品音色",
    scene: "对话女声",
    language: "中文",
    sampleRate: ["8k", "16k", "24k"],
  },
  {
    label: "爱小桃，对话女声(多情感)",
    value: 301038,
    emotions: [
      "中性",
      "平静",
      "兴奋",
      "诗歌",
      "悲伤",
      "生气",
      "恐惧",
      "撒娇",
      "厌恶",
    ],
    type: "精品音色",
    scene: "对话女声",
    language: "中文",
    sampleRate: ["8k", "16k", "24k"],
  },
  {
    label: "爱小萌，对话女声(多情感)",
    value: 301039,
    emotions: [
      "中性",
      "高兴",
      "生气",
      "悲伤",
      "恐惧",
      "广播",
      "平静",
      "兴奋",
      "撒娇",
      "傲娇",
    ],
    type: "精品音色",
    scene: "对话女声",
    language: "中文",
    sampleRate: ["8k", "16k", "24k"],
  },
  {
    label: "爱小星，对话男声(多情感)",
    value: 301040,
    emotions: ["中性", "高兴", "生气", "悲伤", "恐惧", "广播", "兴奋", "解说"],
    type: "精品音色",
    scene: "对话男声",
    language: "中文",
    sampleRate: ["8k", "16k", "24k"],
  },
  {
    label: "爱小菲，对话女声(多情感)",
    value: 301041,
    emotions: ["中性", "生气", "悲伤", "恐惧", "撒娇", "厌恶"],
    type: "精品音色",
    scene: "对话女声",
    language: "中文",
    sampleRate: ["8k", "16k", "24k"],
  },

  // 标准音色
  {
    label: "智逍遥，阅读男声(标准)",
    value: 10510000,
    emotions: ["中性"],
    type: "标准音色",
    scene: "阅读男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智瑜，情感女声(标准)",
    value: 1001,
    emotions: ["中性"],
    type: "标准音色",
    scene: "情感女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智聆，通用女声(标准)",
    value: 1002,
    emotions: ["中性"],
    type: "标准音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智美，客服女声(标准)",
    value: 1003,
    emotions: ["中性"],
    type: "标准音色",
    scene: "客服女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智云，通用男声(标准)",
    value: 1004,
    emotions: ["中性"],
    type: "标准音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智莉，通用女声(标准)",
    value: 1005,
    emotions: ["中性"],
    type: "标准音色",
    scene: "通用女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智琪，客服女声(标准)",
    value: 1008,
    emotions: ["中性"],
    type: "标准音色",
    scene: "客服女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智芸，知性女声(标准)",
    value: 1009,
    emotions: ["中性"],
    type: "标准音色",
    scene: "知性女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智华，通用男声(标准)",
    value: 1010,
    emotions: ["中性"],
    type: "标准音色",
    scene: "通用男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智蓉，情感女声(标准)",
    value: 1017,
    emotions: ["中性"],
    type: "标准音色",
    scene: "情感女声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "智靖，情感男声(标准)",
    value: 1018,
    emotions: ["中性"],
    type: "标准音色",
    scene: "情感男声",
    language: "中文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "WeJack，英文男声(标准)",
    value: 1050,
    emotions: ["中性"],
    type: "标准音色",
    scene: "英文男声",
    language: "英文",
    sampleRate: ["8k", "16k"],
  },
  {
    label: "WeRose，英文女声(标准)",
    value: 1051,
    emotions: ["中性"],
    type: "标准音色",
    scene: "英文女声",
    language: "英文",
    sampleRate: ["8k", "16k"],
  },
];
